[pytest]
DJANGO_SETTINGS_MODULE = saas_app.settings
python_files = test_*.py

# Limit discovery to only these folders
testpaths =
    saas_app/core/tests/tenant
    saas_app/core/tests/platform

markers =
    tenant: mark tests that require tenant context
    platform: mark tests that require platform context
