# Generated by Django 6.0.1 on 2026-02-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audittrail',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
