# Generated by Django 6.0.1 on 2026-02-27 01:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# saas_app.core.migrations.0007_seed_tiers
# saas_app.core.migrations.0013_backfill_tenant_name
# saas_app.core.migrations.0019_alter_platforminvoice_customer
# saas_app.core.migrations.003_seed_tiers

def seed_tiers(apps, schema_editor):
    Tier = apps.get_model("core", "Tier")
    tiers = [
        {"name": "Free", "max_users": 3, "max_locations": 1, "price": 0},
        {"name": "Standard", "max_users": 10, "max_locations": 2, "price": 0},
        {"name": "Premium", "max_users": 50, "max_locations": 10, "price": 5000},
        {"name": "Enterprise", "max_users": 200, "max_locations": 50, "price": 20000},
    ]
    for t in tiers:
        Tier.objects.get_or_create(name=t["name"], defaults=t)


def backfill_tenant_name(apps, schema_editor):
    TenantInvoice = apps.get_model("core", "TenantInvoice")
    for inv in TenantInvoice.objects.filter(tenant_name=""):
        inv.tenant_name = inv.tenant.name
        inv.save()


def set_default_customer(apps, schema_editor):
    PlatformCustomer = apps.get_model("core", "PlatformCustomer")
    PlatformInvoice = apps.get_model("core", "PlatformInvoice")

    default_customer, _ = PlatformCustomer.objects.get_or_create(
        email="default@example.com", defaults={"name": "Default Customer"}
    )
    for inv in PlatformInvoice.objects.filter(customer__isnull=True):
        inv.customer = default_customer
        inv.save()


class Migration(migrations.Migration):

    replaces = [('core', '0001_initial'), ('core', '0002_platformtenantconfig'), ('core', '003_seed_tiers'), ('core', '0004_alter_tenantuser_user'), ('core', '0005_tier_features'), ('core', '0006_remove_tier_hosting_type_and_more'), ('core', '0007_seed_tiers'), ('core', '0008_invoice_tenant'), ('core', '0009_alter_tenantuser_role'), ('core', '0010_platformuser'), ('core', '0011_remove_invoice_tenant_remove_invoice_user_and_more'), ('core', '0012_platformpayment_proof_file_and_more'), ('core', '0013_backfill_tenant_name'), ('core', '0014_platforminvoice_platform_name'), ('core', '0015_platformuser_last_login_platformuser_last_logout_and_more'), ('core', '0016_platforminvoice_description_and_more'), ('core', '0017_platforminvoice_confirmed_at_and_more'), ('core', '0018_platformcustomer_platforminvoice_customer'), ('core', '0019_alter_platforminvoice_customer'), ('core', '0020_alter_platformcustomer_name_and_more'), ('core', '0021_alter_platformcustomer_email_unique')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled', max_length=200)),
                ('type', models.CharField(choices=[('product', 'Product'), ('service', 'Service')], default='product', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('due_date', models.DateField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='platform_invoices/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Project', max_length=200)),
                ('status', models.CharField(default='active', max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled Tenant', max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_users_count', models.IntegerField(default=0)),
                ('current_locations_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_users', models.IntegerField(blank=True, null=True)),
                ('max_locations', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(default=0)),
                ('hosting_type', models.CharField(choices=[('cloud', 'Cloud'), ('onprem', 'On‑Premise')], default='cloud', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('due_date', models.DateField(default=django.utils.timezone.now)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.platforminvoice')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoice_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('line_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.item')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.sale')),
            ],
        ),
        migrations.AddField(
            model_name='platforminvoice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.CreateModel(
            name='TenantCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('due_date', models.DateField(default=django.utils.timezone.now)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='tenant_invoices/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenantcustomer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.tenantinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tenant',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tier'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('invoice_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('provider', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.tenant')),
                ('tier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tier')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformTenantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_type', models.CharField(choices=[('cloud', 'Cloud'), ('local', 'Local')], default='cloud', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_config', to='core.tenant')),
            ],
        ),
       migrations.RunPython(seed_tiers),

        migrations.AlterField(
            model_name='tenantuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tier',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RemoveField(
            model_name='tier',
            name='hosting_type',
        ),
        migrations.AddField(
            model_name='platformtenantconfig',
            name='hosting_type',
            field=models.CharField(choices=[('cloud', 'Cloud'), ('onprem', 'On‑Premise')], default='cloud', max_length=20),
        ),
        migrations.AlterField(
            model_name='tier',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.RunPython(seed_tiers),

        migrations.AlterField(
            model_name='tenantuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('member', 'Member')], default='member', max_length=20),
        ),
        migrations.CreateModel(
            name='PlatformUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('platform_owner', 'Platform Owner'), ('platform_admin', 'Platform Admin'), ('platform_manager', 'Platform Manager'), ('platform_user', 'Platform User')], default='platform_user', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='platforminvoice',
            options={'ordering': ['-issued_at'], 'permissions': [('can_generate_platform_invoice', 'Can generate platform invoices'), ('can_manage_platform_invoice', 'Can edit/delete platform invoices'), ('can_view_platform_invoice', 'Can view platform invoices')]},
        ),
        migrations.AlterModelOptions(
            name='tenantinvoice',
            options={'ordering': ['-issued_at'], 'permissions': [('can_generate_tenant_invoice', 'Can generate tenant invoices'), ('can_manage_tenant_invoice', 'Can edit/delete tenant invoices'), ('can_view_tenant_invoice', 'Can view tenant invoices')]},
        ),
        migrations.AddField(
            model_name='platforminvoice',
            name='audit_log_id',
            field=models.CharField(blank=True, help_text='Reference ID for audit trail', max_length=64),
        ),
        migrations.AddField(
            model_name='platforminvoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantinvoice',
            name='audit_log_id',
            field=models.CharField(blank=True, help_text='Reference ID for audit trail', max_length=64),
        ),
        migrations.AlterField(
            model_name='platforminvoice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='platforminvoice',
            index=models.Index(fields=['tenant', 'status'], name='core_platfo_tenant__a7300b_idx'),
        ),
        migrations.AddIndex(
            model_name='platforminvoice',
            index=models.Index(fields=['due_date'], name='core_platfo_due_dat_8a804d_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantinvoice',
            index=models.Index(fields=['tenant', 'status'], name='core_tenant_tenant__e95bf0_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantinvoice',
            index=models.Index(fields=['due_date'], name='core_tenant_due_dat_2338cc_idx'),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.AddField(
            model_name='platformpayment',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='platform_payments/'),
        ),
        migrations.AddField(
            model_name='platformpayment',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tenantinvoice',
            name='tenant_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenantpayment',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='tenant_payments/'),
        ),
        migrations.AddField(
            model_name='tenantpayment',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='platformpayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_teller', 'Bank Teller'), ('bank_transfer', 'Bank Transfer'), ('paystack', 'Paystack'), ('opay', 'Opay')], max_length=50),
        ),
        migrations.AlterField(
            model_name='platformpayment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tenantpayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_teller', 'Bank Teller'), ('bank_transfer', 'Bank Transfer'), ('paystack', 'Paystack'), ('opay', 'Opay')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tenantpayment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.RunPython(backfill_tenant_name),

        migrations.AddField(
            model_name='platforminvoice',
            name='platform_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='last_logout',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='last_logout',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platforminvoice',
            name='description',
            field=models.TextField(default='Platform invoice generated'),
        ),
        migrations.AddField(
            model_name='tenantinvoice',
            name='description',
            field=models.TextField(default='Invoice generated'),
        ),
        migrations.AddField(
            model_name='platforminvoice',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platforminvoice',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_platform_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='platforminvoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_lodgement', 'Bank Lodgement'), ('bank_transfer', 'Bank Transfer'), ('paystack', 'Paystack'), ('opay', 'Opay')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='platforminvoice',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='tenantinvoice',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantinvoice',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_tenant_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantinvoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_lodgement', 'Bank Lodgement'), ('bank_transfer', 'Bank Transfer'), ('paystack', 'Paystack'), ('opay', 'Opay')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='tenantinvoice',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='platforminvoice',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending'), ('pending_confirmation', 'Pending Confirmation'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('refunded', 'Refunded')], default='pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='platformpayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_lodgement', 'Bank Lodgement'), ('bank_transfer', 'Bank Transfer'), ('paystack', 'Paystack'), ('opay', 'Opay')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tenantinvoice',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending'), ('pending_confirmation', 'Pending Confirmation'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('refunded', 'Refunded')], default='pending', max_length=32),
        ),
        migrations.CreateModel(
            name='PlatformCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='platforminvoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.platformcustomer'),
        ),
        migrations.RunPython(set_default_customer),

        migrations.AlterField(
            model_name='platformcustomer',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='platforminvoice',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.platformcustomer'),
        ),
        migrations.AlterField(
            model_name='platformcustomer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
