# Generated by Django 6.0.1 on 2026-02-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_tenantuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
