# Generated by Django 6.0.1 on 2026-02-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tier_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tier',
            name='hosting_type',
        ),
        migrations.AddField(
            model_name='platformtenantconfig',
            name='hosting_type',
            field=models.CharField(choices=[('cloud', 'Cloud'), ('onprem', 'On‑Premise')], default='cloud', max_length=20),
        ),
        migrations.AlterField(
            model_name='tier',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
