# Generated by Django 6.0.1 on 2026-02-10 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_seed_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.tenant'),
            preserve_default=False,
        ),
    ]
