# Generated by Django 6.0.1 on 2026-02-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_invoice_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
