# Generated by Django 6.0.1 on 2026-02-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_platformuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='platforminvoice',
            options={'ordering': ['-issued_at'], 'permissions': [('can_generate_platform_invoice', 'Can generate platform invoices'), ('can_manage_platform_invoice', 'Can edit/delete platform invoices'), ('can_view_platform_invoice', 'Can view platform invoices')]},
        ),
        migrations.AlterModelOptions(
            name='tenantinvoice',
            options={'ordering': ['-issued_at'], 'permissions': [('can_generate_tenant_invoice', 'Can generate tenant invoices'), ('can_manage_tenant_invoice', 'Can edit/delete tenant invoices'), ('can_view_tenant_invoice', 'Can view tenant invoices')]},
        ),
        migrations.AddField(
            model_name='platforminvoice',
            name='audit_log_id',
            field=models.CharField(blank=True, help_text='Reference ID for audit trail', max_length=64),
        ),
        migrations.AddField(
            model_name='platforminvoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantinvoice',
            name='audit_log_id',
            field=models.CharField(blank=True, help_text='Reference ID for audit trail', max_length=64),
        ),
        migrations.AlterField(
            model_name='platforminvoice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='platforminvoice',
            index=models.Index(fields=['tenant', 'status'], name='core_platfo_tenant__a7300b_idx'),
        ),
        migrations.AddIndex(
            model_name='platforminvoice',
            index=models.Index(fields=['due_date'], name='core_platfo_due_dat_8a804d_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantinvoice',
            index=models.Index(fields=['tenant', 'status'], name='core_tenant_tenant__e95bf0_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantinvoice',
            index=models.Index(fields=['due_date'], name='core_tenant_due_dat_2338cc_idx'),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
