# Generated by Django 6.0.1 on 2026-02-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_invoice_tenant_remove_invoice_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformpayment',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='platform_payments/'),
        ),
        migrations.AddField(
            model_name='platformpayment',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tenantinvoice',
            name='tenant_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenantpayment',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='tenant_payments/'),
        ),
        migrations.AddField(
            model_name='tenantpayment',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='platformpayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_teller', 'Bank Teller'), ('bank_transfer', 'Bank Transfer'), ('paystack', 'Paystack'), ('opay', 'Opay')], max_length=50),
        ),
        migrations.AlterField(
            model_name='platformpayment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tenantpayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_teller', 'Bank Teller'), ('bank_transfer', 'Bank Transfer'), ('paystack', 'Paystack'), ('opay', 'Opay')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tenantpayment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
