# Generated by Django 6.0.1 on 2026-02-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_backfill_tenant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='platforminvoice',
            name='platform_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
