# Generated by Django 6.0.1 on 2026-02-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_platforminvoice_platform_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='last_logout',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='last_logout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
