# Generated by Django 6.0.1 on 2026-02-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_platformuser_last_login_platformuser_last_logout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platforminvoice',
            name='description',
            field=models.TextField(default='Platform invoice generated'),
        ),
        migrations.AddField(
            model_name='tenantinvoice',
            name='description',
            field=models.TextField(default='Invoice generated'),
        ),
    ]
