# Generated by Django 6.0.1 on 2026-02-25 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_platforminvoice_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='platforminvoice',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platforminvoice',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_platform_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='platforminvoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_lodgement', 'Bank Lodgement'), ('bank_transfer', 'Bank Transfer'), ('paystack', 'Paystack'), ('opay', 'Opay')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='platforminvoice',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='tenantinvoice',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantinvoice',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_tenant_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantinvoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_lodgement', 'Bank Lodgement'), ('bank_transfer', 'Bank Transfer'), ('paystack', 'Paystack'), ('opay', 'Opay')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='tenantinvoice',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='platforminvoice',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending'), ('pending_confirmation', 'Pending Confirmation'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('refunded', 'Refunded')], default='pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='platformpayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_lodgement', 'Bank Lodgement'), ('bank_transfer', 'Bank Transfer'), ('paystack', 'Paystack'), ('opay', 'Opay')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tenantinvoice',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending'), ('pending_confirmation', 'Pending Confirmation'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('refunded', 'Refunded')], default='pending', max_length=32),
        ),
    ]
