# Generated by Django 6.0.1 on 2026-02-27 00:18

import django.db.models.deletion
from django.db import migrations, models


def set_default_customer(apps, schema_editor):
    PlatformCustomer = apps.get_model("core", "PlatformCustomer")
    PlatformInvoice = apps.get_model("core", "PlatformInvoice")

    # Create a default customer if not already present
    default_customer, _ = PlatformCustomer.objects.get_or_create(
        name="Default Customer",
        email="default@example.com"
    )

    # Assign default customer to invoices missing one
    PlatformInvoice.objects.filter(customer__isnull=True).update(customer=default_customer)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_platformcustomer_platforminvoice_customer'),
    ]

    operations = [
        # Step 1: Populate missing values
        migrations.RunPython(set_default_customer),

        # Step 2: Alter field to enforce non-null
        migrations.AlterField(
            model_name='platforminvoice',
            name='customer',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='core.platformcustomer',
                null=False,
                blank=False,
            ),
        ),
    ]
