# Generated by Django 6.0.1 on 2026-02-27 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_platforminvoice_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformcustomer',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='platforminvoice',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.platformcustomer'),
        ),
    ]
