# Generated by Django 6.0.1 on 2026-02-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_platformcustomer_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platformcustomer",
            name="name",
            field=models.CharField(max_length=100),  # no uniqueness
        ),
        migrations.AlterField(
            model_name="platformcustomer",
            name="email",
            field=models.EmailField(unique=True),   # enforce uniqueness here
        ),
    ]
