# Generated by Django 6.0.1 on 2026-03-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platforminvoice',
            name='currency',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='tenantinvoice',
            name='currency',
            field=models.CharField(max_length=3),
        ),
    ]
